version: "3.9"

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: "pos123"
    volumes:
      - foodfy-database:/var/lib/postgresql/data/

volumes:
  foodfy-database:
